#!/bin/bash

options=(
	style=round
	width=10.0
	hidpi=off
#	active_color=0xffF08080
	active_color=0xff87ceeb
#	blue_color=0xff414550
#	inactive_color=0xff414550
)

borders "${options[@]}"

# brew services start borders
# brew services restart borders
