#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                on
yabai -m config window_animation_duration    0.0
yabai -m config window_animation_frame_rate  60
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.9
yabai -m config window_opacity_duration      0.2 
yabai -m config split_ratio                  0.5
yabai -m config auto_balance                 off

yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  38
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   06 
#yabai -m config external_bar                all:20:0

# specific space settings

yabai -m signal --add event=window_destroyed actives=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

yabai -m signal --add event=space_changed \
      action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"shenshen-left-jsx\"'"

# Space 1 主屏幕
yabai -m space 1 --label "🌈 Main"

# Space2 开发用的，Microsoft Edge用来开发，以及一些IDE
yabai -m space 2 --label "⌨️  Dev"

# Space 3 ：沟通用
yabai -m space 3 --label "💬 Chat"

# Space 4-6 备用
yabai -m space 4 --label "🏖 Free"
yabai -m space 5 --label "🏖 Free2"
yabai -m space 6 --label "🏖 Free3"
yabai -m space 7 --label "🎸 Media"

# 在副屏上用
yabai -m space 8 --label "🎈 Sec"
yabai -m space 9 --label "🎈 Sec2"

# 临时性的App
otherApp='^(1Password 7|1Password|OmniFocus|查找并替换|访达|SwitchHosts|Alfred Preferences|Raycast|系统设置)$'
topBarApp='^(JetBrains Toolbox)$'
yabai -m rule --add app="${otherApp}" manage=off
yabai -m rule --add app="${topBarApp}" manage=off
yabai -m rule --add app="Parallels Desktop" title="控制中心" manage=off

# 没有正确Sub Window的App
subWindowApp='^(Mail|邮件|Airmail|WeChat|微信|企业咚咚|ME)$'
yabai -m rule --add app="${subWindowApp}" manage=off
#yabai -m signal --add event=window_created app="${subWindowApp}" action="$XDG_CONFIG_HOME/yabai/dongdong.sh"

# regex that matches JetBrains apps
JetBrainsApp='^(IntelliJ IDEA|WebStorm.*|GoLand.*)$'
yabai -m rule --add app="${JetBrainsApp}" manage=off

# iTerm Hotkey Window
yabai -m rule --add app="iTerm2" title=Hotkey.+ manage=off opacity=1
yabai -m rule --add app="iTerm2" title=Main.+ manage=off opacity=1
